name: Test installation with conda

on: 
  # run workflow manually
  workflow_dispatch:
  
jobs:
  build:
    name: Run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest, 
        python-version: ['3.8']
    
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Check envs
        run: conda info --envs
      - name: Activate conda
        run: conda activate test
      - name: Check envs 2
        run: conda info --envs
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install MLJAR AutoML
        run: conda install -c conda-forge mljar-supervised
      - name: Try to import
        run: python -c "from supervised.automl import AutoML"
