name: Test installation with conda

on: 
  # run workflow manually
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        cfg:
        - { platform: linux, platform_name: Linux,  os: ubuntu-latest }
        - { platform: mac, platform_name: macOS, os: macos-latest }
        - { platform: win, platform_name: Windows, os: windows-latest }
        python_version: [3.7, 3.8, 3.9]
    
    name: '${{ matrix.cfg.platform_name }} tests with Python ${{ matrix.python_version }}'
    runs-on: ${{ matrix.cfg.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          conda install -c conda-forge mljar-supervised
      - name: Try to load MLJAR AutoML
        run: |
          python -v
          python -c "from supervised.automl import AutoML"

    
  
